services:
  front-end:
    build: ./front-end
    container_name: front-end_c
    ports:
      - '80:80'
  back-end:
    build: ./back-end
    container_name: back-end_c
    ports:
      - '3000:3000'
    volumes:
      - ./back-end:/app