name: Water Watch CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install frontend dependencies
        working-directory: ./front-end
        run: npm install

      - name: Run frontend tests with increased memory
        working-directory: ./front-end
        run: node --max-old-space-size=4096 node_modules/.bin/vitest run

      - name: Build frontend
        working-directory: ./front-end
        run: npm run build

  build-and-test-backend:
    runs-on: ubuntu-latest
    needs: build-and-test-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for back-end
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install backend dependencies
        working-directory: ./back-end
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        id: add-ssh-key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.REPO_PATH }}
            git pull origin main
            cd front-end
            npm install
            npm run build
            sudo systemctl restart nginx
          EOF
